### PR TITLE
is-plain-object -> is-plain-obj

### LINKED ISSUE #3: is-plain-object -> is-plain-obj
I don't suppose I could convince you to switch from is-plain-object to is-plain-obj (prior to the upcoming ES2015 rewrite)? 

As part of my (somewhat an*l) byte-hunt, I found that is-plain-obj had a smaller footprint than is-plain-object, and assisted a great deal in deduping the amount of dependencies rolled out for a distribution build (obviously that depends entirely on the dependency graph of each project). 

I'm currently using [kasperlewau/obj-clean/tree/replace-is-plain-object](https://github.com/kasperlewau/obj-clean/tree/replace-is-plain-object) to satisfy this 'need'.

### PR DESCRIPTION
**Pull request by kasperlewau**
closes #3

### CODE REVIEW

**Comment by SamVerschueren** [comment]
You have to change the import in `index.js` as well.

**Comment by kasperlewau** [comment]
:man_facepalming: 

incoming!

**Comment by SamVerschueren** [comment]
Nice. Will release tomorrow, now on mobile.

**Comment by kasperlewau** [comment]
Cool! Looking forward to it.

**Comment by SamVerschueren** [comment]
Released as `1.1.1`. ES2015 version is coming up as `2.0.0`.

Thanks @kasperlewau!

**Comment by kasperlewau** [comment]
Thank you!

**Pull request merged**
